### ISSUE TITLE
Trouble connecting to badge server

### ISSUE THREAD

**Issue by leninlal** [iblstudios/IBLOpenBadges-xBlock#9]
hi,
 i've implemented IBL Open badges server in my local env, successfully installed and configured the xblock. After adding xblock as a course content, how can i retrieve token from the server ? 

here, attaching the image after adding xblock as course content.
![xblock](https://cloud.githubusercontent.com/assets/7258851/9247819/fcb76436-41d3-11e5-92d4-9e852445806c.png)

**Comment by labarba** [comment]
You don't say if you did this, but: you have to first create a badge in the badge server (Dahsboard>Issue Badges>Add Badge). Once the badge is added, the badge server will generate the keys that you need to enter in the Edit dialog of the Xblock course content.

**Comment by leninlal** [comment]
here is the pic of my dashboard
![badgeone](https://cloud.githubusercontent.com/assets/7258851/9249140/f99272e4-41df-11e5-8aea-cb04dcafba76.png)
it doesn't have issue badges

**Comment by labarba** [comment]
You need to be made an "Issuer" by the admin of the badge server. Or if what you're showing me is your Dashboard as an admin, you need to open another (regular) account that you will use to issue badges, then log in as admin, and go to Users to make that account an "Issuer."

Then add a badge from the Issuer account.

**Comment by leninlal** [comment]
@labarba  thanks for the help.it worked.
